### ISSUE TITLE
GSL interface not compatible with GSL version >= 2.0

### ISSUE THREAD

**Issue by lambe** [optimizers/cutest-mirror#2]
Because of API changes to GSL, the following errors are observed when compiling CUTEst:

```
gsl_main.c: In function ‘main’:
gsl_main.c:408:44: error: ‘gsl_multifit_fdfsolver {aka struct <anonymous>}’ has no member named ‘J’
     grad_status = gsl_multifit_gradient(gsl->J, gsl->f, gradient);
                                            ^
gsl_main.c:449:47: error: ‘gsl_multifit_fdfsolver {aka struct <anonymous>}’ has no member named ‘J’
        grad_status = gsl_multifit_gradient(gsl->J, gsl->f, gradient);
                                               ^
```

Similar errors have been reported for other projects, e.g., [https://github.com/samtools/bcftools/issues/387](url)

The optimizer using GSL should be updated to account for the new interface.

**Comment by dpo** [comment]
Thanks for the report. Currently we only support GSL 1. [This automated installer](https://github.com/abelsiqueira/linux-cutest) will pull the correct dependencies for you.
